version: '2'

services:

  nginx:
    image: nginx:latest
    ports:
      - "777:80"
    networks:
      - main

  php:
    image: devdrops/php-fpm:7.0
    volumes:
      - ./app:/var/www/html
    networks:
      - main

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    volumes:
      - data:/var/lib/mysql
    networks:
      - main
    ports:
      - "3307:3306"

networks:

  main:
    driver: 'bridge'

volumes:

  data:
    driver: 'local'
